pipeline {
    agent any
    stages {
        stage('Pull Code') {
            steps {
                checkout scm
            }
        }
        stage('deploy') {
            steps {
                sh '''
                docker-compose -f docker-compose-build.yml build backend
                docker-compose -f docker-compose-deploy.yml up -d backend
                '''
            }
        }


        stage('Notification') {
            steps {
                echo 'all state success'
            }
        }
    }
}